import {
	  Button,
	  Select,
	  Form,
	  FormItem,
	  Input,
	  Container,
	  Menu,
	  Aside,
	  Main,
	  Popover,
	  Dropdown,
	  DropdownMenu,
	  DropdownItem,
	  Calendar,
	  Row,
	  Option,
	  Submenu,
	  MenuItemGroup,
	  MenuItem,
		Tree,
		Dialog,
		Image,
		Table,
		TableColumn,
		Link,
		Switch,
		Pagination,
		Checkbox,
		CheckboxButton,
		CheckboxGroup,
		Tabs,
		TabPane,
		Upload,
		Col,
		RadioGroup,
		DatePicker,
		Radio,
		Alert,
		ColorPicker
	} from "element-ui"

const coms = [Button, Select, Form, Input, FormItem, Aside, Main, Container, Menu, Option, Row, Calendar,DropdownMenu,DropdownItem,Submenu,Popover,MenuItemGroup,MenuItem,Tree,Dropdown,Dialog,Image,Table,
		TableColumn,Link,Switch,Pagination,Checkbox,CheckboxGroup,CheckboxButton,Tabs,TabPane,Upload,Col,RadioGroup,DatePicker,Radio,Alert,ColorPicker
]
export default coms
